version: "3.8"
services:
  db:
    image: postgres:16
    container_name: pricing_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: pricing
    ports:
      - "5435:5432"
    volumes:
      - pgdata_pricing:/var/lib/postgresql/data
volumes:
  pgdata_pricing:
